name: flutter_fortune_wheel
version: 1.3.1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_hooks: ^0.18.6
  flutter_svg: ^2.0.10+1
  quiver: ^3.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  effective_dart: ^1.3.2

